language: csharp
dist: trusty
sudo: required
dotnet: 2.0.0
install:
  - export DOTNET_CLI_TELEMETRY_OUTPUT=1
before_script:
  - chmod a+x ./build.sh
script:
  - ./build.sh
addons:
  apt:
    sources:
    - sourceline: 'deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod trusty main'
      key_url: 'https://packages.microsoft.com/keys/microsoft.asc'
    packages:
    - dotnet-hostfxr-1.0.1
    - dotnet-sharedframework-microsoft.netcore.app-1.1.2